:version: 0.3.0
:apVersion: 2.5.0
:tscVersion: 1.6.2
= TypeScript Asset-Pipeline

The `typescript-asset-pipeline` is an https://github.com/bertramdev/asset-pipeline-core[Asset Pipeline] module that compiles TypeScript files using v{tsVersion} of the compiler.

NOTE: This is a work in progress and will need more extensive testing, performance improvements, etc. *Until version 1.0 it should not be considered production ready.*

== Getting Started

=== Gradle / Grails 3

[source,groovy,subs='attributes']
.build.gradle
----
plugins {
    id 'com.bertramlabs.asset-pipeline' version '{apVersion}'
}

dependencies {
    assets 'com.craigburke:typescript-asset-pipeline:{version}'
}
----

=== Grails 2
[source,groovy,subs='attributes']
.BuildConfig.groovy
----
dependencies {
    compile 'com.craigburke:typescript-asset-pipeline:{version}' 
}

----

== How it Works

This plugin will compile any file with a `.ts` extension into corresponding JavaScript. It also supports the use of declaration files (`d.ts`).

== Configuration

You can set additional compiler options by setting the **typeScript** map.

[source,groovy]
.build.gradle
----
assets {
    configOptions: [
        typeScript: [
           module:'commonjs' // <1>
           target:'es5'
           experimentalDecorators:true // <2>
        ]
    ]
}
----
<1> This translates to `--module commonjs`
<2> Since a boolean is provided as the value, this is treated as a flag and translates to `--experimentalDecorators`

See: https://github.com/Microsoft/TypeScript/wiki/Compiler-Options